### ISSUE TITLE
Unable to build using Cloudflare pages

### ISSUE THREAD

**Issue by RenaudDev** [opera7133/Blonde#123]
Hi,

I was able to build with Netlify, but all my stack is on Cloudflare using Cloudflare pages...which is a lot more performant in my experience. Somehow there seems to be a problem with POSTCSS

Here is the log
```
<html>
<body>
<!--StartFragment-->

09:46:53.061 | Cloning repository...
-- | --
09:46:54.129 | From https://github.com/RenaudDev/newWebsite
09:46:54.130 | * branch            74070b7cb2f93d0433090db88ae3e3f8b7fbba40 -> FETCH_HEAD
09:46:54.130 |  
09:46:54.174 | HEAD is now at 74070b7 Init 4
09:46:54.175 |  
09:46:57.683 | Submodule 'themes/Blonde' (https://github.com/opera7133/Blonde.git) registered for path 'themes/Blonde'
09:46:57.683 | Cloning into '/opt/buildhome/clone/themes/Blonde'...
09:46:57.684 | Submodule path 'themes/Blonde': checked out '4abdcfd60616711b5392e43da5a60aad6d85d575'
09:46:57.684 |  
09:46:57.709 | Success: Finished cloning repository files
09:46:58.300 | Installing dependencies
09:46:58.313 | Python version set to 2.7
09:47:02.309 | v12.18.0 is already installed.
09:47:03.731 | Now using node v12.18.0 (npm v6.14.4)
09:47:04.085 | Started restoring cached build plugins
09:47:04.102 | Finished restoring cached build plugins
09:47:04.827 | Attempting ruby version 2.7.1, read from environment
09:47:10.873 | Using ruby version 2.7.1
09:47:11.272 | Using PHP version 5.6
09:47:11.460 | 5.2 is already installed.
09:47:11.491 | Using Swift version 5.2
09:47:11.492 | Started restoring cached node modules
09:47:11.514 | Finished restoring cached node modules
09:47:11.771 | Installing NPM modules using NPM version 6.14.4
09:47:18.333 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
09:47:18.334 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
09:47:18.334 |  
09:47:18.335 | added 115 packages from 137 contributors and audited 116 packages in 5.649s
09:47:18.376 |  
09:47:18.377 | 26 packages are looking for funding
09:47:18.377 | run `npm fund` for details
09:47:18.377 |  
09:47:18.378 | found 0 vulnerabilities
09:47:18.378 |  
09:47:18.394 | NPM modules installed
09:47:18.795 | Installing Hugo 0.89.0
09:47:19.988 | hugo v0.89.0-ADE966B8+extended linux/amd64 BuildDate=2021-11-02T10:00:18Z VendorInfo=gohugoio
09:47:19.995 | Started restoring cached go cache
09:47:20.020 | Finished restoring cached go cache
09:47:20.197 | go version go1.14.4 linux/amd64
09:47:20.219 | go version go1.14.4 linux/amd64
09:47:20.224 | Installing missing commands
09:47:20.225 | Verify run directory
09:47:20.225 | Executing user command: git submodule update --remote --merge && npm run build
09:47:21.188 |  
09:47:21.188 | > Blonde@0.0.2 build /opt/buildhome/repo
09:47:21.189 | > tailwindcss -i ./themes/Blonde/assets/css/main.css -o ./themes/Blonde/assets/css/style.css && hugo --minify
09:47:21.189 |  
09:47:24.020 |  
09:47:24.021 | Done in 1268ms.
09:47:24.102 | Start building sites …
09:47:24.102 | hugo v0.89.0-ADE966B8+extended linux/amd64 BuildDate=2021-11-02T10:00:18Z VendorInfo=gohugoio
09:47:24.262 | Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): (node:1450) ExperimentalWarning: The ESM module loader is experimental.
09:47:24.262 | internal/modules/run_main.js:54
09:47:24.263 | internalBinding('errors').triggerUncaughtException(
09:47:24.263 | ^
09:47:24.263 |  
09:47:24.263 | Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
09:47:24.263 | at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:720:11)
09:47:24.263 | at Loader.resolve (internal/modules/esm/loader.js:97:40)
09:47:24.263 | at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
09:47:24.263 | at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
09:47:24.263 | at link (internal/modules/esm/module_job.js:41:36) {
09:47:24.264 | code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
09:47:24.264 | }
09:47:24.264 | Total in 183 ms
09:47:24.273 | npm ERR! code ELIFECYCLE
09:47:24.273 | npm ERR! errno 255
09:47:24.274 | npm ERR! Blonde@0.0.2 build: `tailwindcss -i ./themes/Blonde/assets/css/main.css -o ./themes/Blonde/assets/css/style.css && hugo --minify`
09:47:24.274 | npm ERR! Exit status 255
09:47:24.274 | npm ERR!
09:47:24.274 | npm ERR! Failed at the Blonde@0.0.2 build script.
09:47:24.274 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
09:47:24.287 |  
09:47:24.287 | npm ERR! A complete log of this run can be found in:
09:47:24.288 | npm ERR!     /opt/buildhome/.npm/_logs/2022-06-02T13_47_24_275Z-debug.log
09:47:24.299 | Failed: build command exited with code: 255
09:47:24.993 | Failed: an internal error occurred

<!--EndFragment-->
</body>
```
</html>

**Comment by opera7133** [comment]
Try increasing your Node.js version to 14 or higher.
To change the version, go to your Cloudflare Pages settings and specify an environment variable named NODE_VERSION.
https://developers.cloudflare.com/pages/platform/build-configuration/#language-support-and-tools
