### ISSUE TITLE
difficulty with installation

### ISSUE THREAD

**Issue by esquires** [opera7133/Blonde#40]
I am having some difficulty with the installation of the repo. Here are the steps I took

```bash
git clone https://github.com/opera7133/Blonde 
cd Blonde/exampleSite
mkdir themes
cd themes
git clone https://github.com/opera7133/Blonde 
cd ..

sudo npm install -g postcss postcss-cli autoprefixer

npm install
hugo server
```

From here I get the following error:

```bash

Start building sites …
Built in 970 ms
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): TypeError: Object.entries(...).flatMap is not a function
    at flattenColorPalette (/home/esquires/tmp/Blonde/exampleSite/node_modules/tailwindcss/lib/util/flattenColorPalette.js:8:83)
    at /home/esquires/tmp/Blonde/exampleSite/node_modules/tailwindcss/lib/plugins/divideColor.js:27:53
    at plugins.forEach.plugin (/home/esquires/tmp/Blonde/exampleSite/node_modules/tailwindcss/lib/util/processPlugins.js:69:5)
    at Array.forEach (<anonymous>)
    at _default (/home/esquires/tmp/Blonde/exampleSite/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
    at /home/esquires/tmp/Blonde/exampleSite/node_modules/tailwindcss/lib/processTailwindFeatures.js:64:54
    at LazyResult.runOnRoot (/home/esquires/tmp/Blonde/exampleSite/node_modules/postcss/lib/lazy-result.js:333:16)
    at LazyResult.runAsync (/home/esquires/tmp/Blonde/exampleSite/node_modules/postcss/lib/lazy-result.js:385:26)


```

Any ideas on what I might be doing wrong? Thanks!

**Comment by opera7133** [comment]
Are you using an older Node.js (v11 or earlier)?
I found an Issue similar to this one.

- https://github.com/gatsbyjs/gatsby/issues/28173
- https://stackoverflow.com/questions/64907613/typeerror-object-entries-flatmap-is-not-a-function

**Comment by esquires** [comment]
Thanks! I should have mentioned I was on node 14.7. However, it turns out that there are some issues with the snap package. See [here](https://discourse.gohugo.io/t/postcss-error-on-build-tailwind-css/32728) for more details. I ended up installing the binary deb package instead and was able to the example site.
