### ISSUE TITLE
POSTCSS: failed to transform "css/styles.css" (text/css):  ...test/themes/Blonde/node_modules/color/index.js:257

### ISSUE THREAD

**Issue by yubaoliu** [opera7133/Blonde#66]
```sh
hugo v0.89.0-DEV+extended linux/amd64 BuildDate=unknown
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): /home/yubao/Project/Website/test/themes/Blonde/node_modules/color/index.js:257
                        lum[i] = (chan <= 0.039_28) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;
                                          ^^^^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/yubao/Project/Website/test/themes/Blonde/node_modules/tailwindcss/lib/util/pluginUtils.js:25:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Built in 479 ms
```

**Comment by opera7133** [comment]
Perhaps it's because you have an older version of Node.js.
Try upgrading to a newer version.

**Comment by yubaoliu** [comment]
Thanks
